import { ReactNode } from "react";
import type {
  AppMailProps,
  AppMailReplyProps,
  AppMailSidebarItem,
  ChartDataState,
  ChartOptionsState,
  CustomEvent,
  Demo,
  LayoutType,
  MailKeys,
  SortOrderType,
} from "./demo";

import {
  Abonnement,
  AppBreadcrumbProps,
  AppConfigProps,
  AppMenuItemProps,
  AppTopbarRef,
  Breadcrumb,
  BreadcrumbItem,
  ChatContextProps,
  ColorScheme,
  LayoutConfig,
  LayoutContextProps,
  LayoutState,
  MailContextProps,
  MenuContextProps,
  MenuModel,
  MenuProps,
  NodeRef,
  Page,
  TaskContextProps,
  UseSubmenuOverlayPositionProps,
  UserContextProps,
  User,
} from "./layout";

type ChildContainerProps = {
  children: ReactNode;
};

export type {
  Abonnement,
  AppBreadcrumbProps,
  AppConfigProps,
  AppMailProps,
  AppMailReplyProps,
  AppMailSidebarItem,
  AppMenuItemProps,
  AppTopbarRef,
  Breadcrumb,
  Breadcrumb,
  BreadcrumbItem,
  ChartDataState,
  ChartOptionsState,
  ChatContextProps,
  ChildContainerProps,
  ColorScheme,
  CustomEvent,
  Demo,
  LayoutConfig,
  LayoutContextProps,
  LayoutState,
  LayoutType,
  MailContextProps,
  MailKeys,
  MenuContextProps,
  MenuModel,
  MenuProps,
  NodeRef,
  Page,
  SortOrderType,
  TaskContextProps,
  UseSubmenuOverlayPositionProps,
  UserContextProps,
  User,
};
